POST http://localhost:5142/_query

CREATE DATABASE abc

###

POST http://localhost:5142/_query

CREATE TABLE abc.def (a TEXT, b TEXT, c INT, d FLOAT)

###

POST http://localhost:5142/_query

INSERT INTO abc.def ( b, a, c, d) VALUES ('Hello, world!', '456', 123, 0.123)


###

POST http://localhost:5142/_query

SELECT * FROM abc.def



###
GET http://localhost:5142/

###
GET http://localhost:5142/abc